; PlatformIO Configuration
; ESP Monitor — INA219 energy measurement

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
monitor_filters = time, esp32_exception_decoder

lib_deps =
    adafruit/Adafruit INA219@^1.2.1
    adafruit/Adafruit BusIO@^1.16.1

build_flags = -I include

;upload_port = COM3
;monitor_port = COM3
upload_speed = 921600
