; PlatformIO Configuration

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
monitor_filters = time, esp32_exception_decoder

lib_deps =
    kosme/arduinoFFT@^2.0.2
    knolleary/PubSubClient@^2.8
    jgromes/RadioLib@^7.1.2


build_flags = -I include

upload_port = COM3
monitor_port = COM3
upload_speed = 921600
